# ToDo - check version
version: '3.8'

services:
  dbdatasrv:
    container_name: dbdata_cnt
    build: 
      context: .
      dockerfile: datasrv/Dockerfile
    image: epi_dbdata:1.0
    restart: always
    environment:
      DATABASE_HOST: ${DB_HOST} 
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:${DB_PORT}"
    networks:
      - kuipernet
 
  pgadmin:
    container_name: dbadminer_cnt
    build: 
      context: .
      dockerfile: dbadminer/Dockerfile
    image: epi_dbadminer:1.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    depends_on:
      - dbdatasrv
    ports:
    - "8082:${PGADMIN_PORT}"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "dbdatasrv:pgsql-server"
    networks:
      - kuipernet

  andro:
    container_name: andro_cnt
    build:
      context: .
      dockerfile: andro/Dockerfile
    image: epi_andro:1.0
    restart: always
    environment:
      ANDRO_APP_HOST: ${AN_APP_HOST}
      ANDRO_DB_HOST: ${AN_DB_HOST}
      ANDRO_DB_DRIVER: ${AN_DB_DRIVER}
      ANDRO_DB_NAME: ${AN_DB_NAME}
      ANDRO_DB_USER: ${AN_DB_USER}
      ANDRO_DB_PASS: ${AN_DB_PASS}
      ANDRO_DB_PORT: ${AN_DB_PORT}
      ANDRO_DB_URL: "postgres://${AN_DB_USER}:${AN_DB_PASS}@${AN_DB_HOST}:${AN_DB_PORT}/${AN_DB_NAME}?sslmode=disable"
      ANDRO_APP_USER: ${AN_APP_USER}
      ANDRO_APP_PASS: ${AN_APP_PASS}
      ANDRO_APP_PORT: ${AN_APP_PORT}
      ANDRO_API_JWT_SECRET: ${AN_API_JWT_SECRET}
    ports:
    - "8081:${AN_APP_PORT}"
    depends_on:
      - dbdatasrv
    networks:
      - kuipernet

  websrv:
    container_name: websrv_cnt
    build: 
      context: .
      dockerfile: websrv/Dockerfile
    image: epi_websrv:1.0
    restart: always
    volumes:
      - ./quark/dist:/usr/share/nginx/html
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - andro
    networks:
      - kuipernet

# Volumes to be created to facilitate data persistance 
volumes:
  db-data:
  pgadmin-data:

# Networks to be created to facilitate communication between containers
networks:
  kuipernet:
    driver: bridge
